!cxx
E0+unexpectedEof++unexpected end of file
E0+invalidChar++invalid character
E0+unknownHash++invalid character after '#'
E1+unknownNamedConstant++unknown #! named constant %1
E1+unexpectedToken++unexpected token %1
E0+unterminatedString++string with no closing quote
E0+missingCloseParen++missing closing parenthesis
E1+invalidNumber++invalid number %1
E1+invalidAfiiGlyphId++invalid AFII glyph identifier %1
E1+callNonFunction++call of non-function object %1
E0+tooManyArgs++too many arguments for function
E0+oddKeyArgs++odd number of keyword/value arguments
E0+missingArg++missing argument for function call
E1+syntacticKeywordAsVariable++syntactic keyword %1 used as variable
E1+undefinedVariableReference++reference to undefined variable %1
E0+badCharName++no character with that name
E1+keywordNotAllowedCall++syntactic keyword %1 not valid in call position
E1+symbolRequired++symbol required (got %1)
E1+unknownTopLevelForm++unknown top level form %1
E1+badModeForm++bad form %1 in mode group
E1+duplicateDefinition++identifier %1 already defined in same part+first definition was here
E1+identifierLoop++loop in specification of value of %1
E0+outOfRange++argument out of range
E1+unitLoop++loop in specification of value of unit %1
E1+badUnitDefinition++bad value specified for unit %1
E1+duplicateUnitDefinition++unit %1 already defined in same part+first definition was here
E1+undefinedQuantity++quantity %1 undefined
E0+incompatibleDimensions++incompatible dimensions
E3+notABoolean++%2 argument for primitive %1 of wrong type: %3 not a boolean
E3+notAPair++%2 argument for primitive %1 of wrong type: %3 not a pair
E3+notAList++%2 argument for primitive %1 of wrong type: %3 not a list
E3+notASymbol++%2 argument for primitive %1 of wrong type: %3 not a symbol
E3+notAString++%2 argument for primitive %1 of wrong type: %3 not a string
E3+notAStringOrSymbol++%2 argument for primitive %1 of wrong type: %3 not a string or symbol
E3+notASymbolOrString++%2 argument for primitive %1 of wrong type: %3 neither a string not a symbol
E3+notAChar++%2 argument for primitive %1 of wrong type: %3 not a char
E3+notAStyle++%2 argument for primitive %1 of wrong type: %3 not a style
E3+notAnExactInteger++%2 argument for primitive %1 of wrong type: %3 not an exact integer
E3+notAQuantity++%2 argument for primitive %1 of wrong type: %3 not a quantity
E3+notAColorSpace++%2 argument for primitive %1 of wrong type: %3 not a color-space
E3+notANumber++%2 argument for primitive %1 of wrong type: %3 not a number
E3+notASosofo++%2 argument for primitive %1 of wrong type: %3 not a sosofo
E3+notAnOptSingletonNode++%2 argument for primitive %1 of wrong type: %3 not an optional singleton node list
E3+notASingletonNode++%2 argument for primitive %1 of wrong type: %3 not a singleton node list
E3+notANodeList++%2 argument for primitive %1 of wrong type: %3 not a node list
E3+notANamedNodeList++%2 argument for primitive %1 of wrong type: %3 not a named node list
E3+notALengthSpec++%2 argument for primitive %1 of wrong type: %3 not a length or length-spec
E3+notAQuantityOrLengthSpec++%2 argument for primitive %1 of wrong type: %3 not a quantity or length-spec
E3+notAPriority++%2 argument for primitive %1 of wrong type: %3 not an integer or the symbol "force"
E3+notAPattern++%2 argument for primitive %1 of wrong type: %3 not a valid element matching pattern
E3+notAnAddress++%2 argument for primitive %1 of wrong type: %3 not an address
E3+notAGlyphId++%2 argument for primitive %1 of wrong type: %3 not a glyph-id
E3+notAGlyphSubstTable++%2 argument for primitive %1 of wrong type: %3 not a glyph-subst-table
E3+notAGlyphIdPairList++%2 argument for primitive %1 of wrong type: %3 not a list of pairs of glyph-ids
E3+notAProcedure++%2 argument for primitive %1 of wrong type: %3 not a procedure
E3+notAVector++%2 argument for primitive %1 of wrong type: %3 not a vector
E0+duplicateRootRule++root rule already defined in same part with same importance+first definition was here
E1+duplicateInitialValue++initial value already declared for characteristic %1 in same part+first declaration was here
E1+invalidStyleKeyword++%1 is not a valid keyword in a style expression
E2+invalidMakeKeyword++%1 is not a valid keyword in a make expression for flow object class %2
E1+unknownFlowObjectClass++%1 is not the name of any flow object class
E1+atomicContent++content expression cannot be specified in make expression for atomic flow object class %1
E0+labelNotASymbol++value for "label:" not a symbol
E1+badConnection++no port for label %1
E0+badContentMap++invalid content map
E1+contentMapBadPort++content map references non-existent port %1
E1+invalidCharacteristicValue++invalid value for %1 characteristic
E0+condFail++no clause in cond expression matched
E1+caseFail++no clause in case expression matched %1
E1+caseElse++expected "else" not %1
E0+caseUnresolvedQuantities++sorry, cannot handle unresolvable quantities in datums in case expression
E1+errorProc++%1
E0+divideBy0++division by zero
E1+invalidKeyArg++procedure does not have %1 keyword argument
E0+keyArgsNotKey++argument not a keyword
E0+oneBody++support for more than one style-specification-body not yet implemented
E0+specNotArc++specification document does not have the DSSSL architecture as a base architecture
E0+noStyleSpec++specification document did not contain a style-specification-body element
E1+unknownCharName++unknown character name %1
E0+noCurrentNode++attempt to use current node when there is none
E0+noCurrentProcessingMode++attempt to process node in illegal context
E0+invalidRadix++radix must be 2, 8, 10 or 16
E0+sosofoContext++this context requires a sosofo
E0+styleContext++this context requires a style object
E0+notInCharacteristicValue++procedure can only be used in evaluation of characteristic value
E1+expressionNotImplemented++sorry, %1 expression not implemented
E0+RGBColorArgCount++Device RGB color requires three arguments
E0+RGBColorArgType++arguments for Device RGB color must be numbers
E0+RGBColorArgRange++arguments for Device RGB color must be in the range 0 to 1
E1+unknownColorSpaceFamily++unknown color-space family %1
E0+deviceRGBColorSpaceNoArgs++Device RGB Color Space Family does not take any arguments
E1+notABuiltinInheritedC++%1 is not a pre-defined inherited characteristic
E1+invalidNumberFormat++invalid number format %1
E1+invalidPublicIdChar++invalid character %1 in public identifier
I1+debug++debug %1
E0+useLoop++circular use of specification parts
E1+missingPart++no style-specification or external-specification with ID %1
E0+noParts++document did not contain any style-specifications or external-specifications
E0+tableCellOutsideTable++table-cell flow object not inside a table
E0+tableRowOutsideTable++table-row flow object not inside a table
E1+noNodePropertyValue++no value for node property %1
E0+returnNotNodeList++value returned by procedure was not a node-list
I0+stackTrace++called from here
I1+stackTraceEllipsis++called from here...(%1 calls omitted)
E0+processNodeLoop++node processing loop detected
E0+spliceNotList++unquote-splicing expression does not evaluate to a list
E0+readOnly++object is read-only
E1+topLevelAssignment++assignment to top-level variable %1
E0+continuationDead++invalid call to continuation
E0+patternEmptyGi++empty generic identifier in pattern
E0+patternNotList++pattern is not a list
E1+patternBadGi++%1 cannot be used as a generic identifier in a pattern
E1+patternBadMember++%1 cannot occur in a pattern
E0+patternMissingQualifierValue++value missing for qualifier in pattern
E1+patternUnknownQualifier++unknown pattern qualifier %1
E2+patternBadQualifierValue++bad value %1 for %2 qualifier in pattern
E0+patternChildRepeat++repeat qualifier not allowed inside children qualifier
E0+patternBadAttributeQualifier++bad value for attributes qualifier in pattern
E1+ambiguousStyle++characteristic %1 applied in style rule with same specificity+other style rule is here
E0+ambiguousMatch++node matches more than one pattern with the same specificity
E1+uninitializedVariableReference++reference to uninitialized variable %1
E1+actualLoop++circular use of actual value of characteristic %1
E1+duplicateCharacteristic++characteristic %1 already defined in same part+first definition was here
E1+duplicateFlowObjectClass++flow object class %1 already defined in same part+first definition was here
E1+undefinedMode++mode %1 not defined

