#
# 
#
# Common Command messages
#
0
#
commandFailed          Command execution failed: %0
commandExec            Executing already executed command!
commandUnExec          Unexecuting not executed command!
macroCmdSub            MacroCommand contains no subcommands
cmdLinkNoLink          CommandLink has no linked command
cmdLinkFirstCmd        CommandLink: primary command execution error
cmdLinkSecondCmd       CommandLink: secondary command execution error
cmdLinkSecondCmdUnExec CommandLink: secondary command unexecution error
cmdLinkFirstCmdUnExec  CommandLink: primary command unexecution error
cmdAddNull             Attempt to add null sub-command to macro command
