# Copyright (c) 1997 James Clark
# See the file COPYING for copying permission

=5000

W0+unsupportedPageNumberNonElement++TeX backend does not currently support references to page numbers of nodes other than elements
W0+unsupportedLinkNonElement++TeX backend does not currently support links to nodes other than elements
W0+unsupportedLinkEntity++TeX backend does not currently support links to entities
W0+unsupportedLinkSgmlDoc++TeX backend does not currently support links to other SGML documents
W0+unsupportedLinkHyTime++TeX backend does not currently support HyTime linkends
W0+unsupportedLinkTei++TeX backend does not currently support TEI links
W0+unsupportedLinkHtml++TeX backend does not currently support HTML links
W0+unsupportedGlyphSubstTable++TeX backend does not currently support glyph substitution tables
