#
# 
#
# Catalog Manager messages
#
9
#
##################################################################
#
unknownError            An unknown error occurred while processing catalog '%0'
#
# Catalog building messages
#
cantBuildGrove          Cannot parse catalog file '%0'
invalidCatalogFile      File '%0' is not an XML catalog
catalogFileDoesNotExist Catalog file '%0' does not exist
#
reqAttributeMissing     Required attribute '%0' missing in the catalog element '%1'
unknownCatalogEntry     An unknown catalog entry '%0' is encountered
urnSysidAndPubidDiffer  A system identifier '%0' is in URN namespace and is not equal to public identifier '%1'
circularReference       Circular reference to catalog '%0' detected, while processing catalog '%1'
