# Copyright (c) 1997 James Clark
# See the file COPYING for copying permission.

# XmlOutput message definitions
=100
W1+sdataEntityReference++reference to internal SDATA entity %1 not allowed in XML
W1+externalDataEntityReference++reference to external data entity %1 not allowed in XML
W1+subdocEntityReference++reference to subdocument entity %1 not allowed in XML
W0+piQuestionLt++processing instruction containing "?>" not allowed in XML
W0+piNoName++XML requires processing instructions to start with a name
W1+externalDataNdata++external data entity %1 is CDATA or SDATA, but XML allows only NDATA
W1+notationAttributes++attributes were defined for notation %1; not allowed in XML
W1+cannotConvertFsiToUrl++cannot convert formal system identifier %1 to URL
