
debug:PACKAGE_CFG_OPTIONS += --enable-debug
PACKAGE_CFG_ENV           += LD_LIBRARY_PATH=$$THIRD_DIR/lib:${LD_LIBRARY_PATH}
darwin:PACKAGE_CFG_ENV    += DYLD_LIBRARY_PATH=$$THIRD_DIR/lib:${DYLD_LIBRARY_PATH}

PACKAGE_MAKE_ENV           += LD_LIBRARY_PATH=$$THIRD_DIR/lib:${LD_LIBRARY_PATH}
darwin:PACKAGE_MAKE_ENV    += DYLD_LIBRARY_PATH=$$THIRD_DIR/lib:${DYLD_LIBRARY_PATH}
