# Copyright (c) 1996 James Clark
# See the file COPYING for copying permission.

# CmdLineApp message definitions

=4000
E1+invalidOptionError++invalid option %1
E1+missingOptionArgError++missing argument for option %1
I1+usage++usage is %1
I1+versionInfo++SP version %1
E1+unknownBctf++unknown BCTF %1
E1+unknownEncoding++unknown encoding %1
E2+openFileError++cannot open output file %1 (%2)
E2+closeFileError++cannot close output file %1 (%2)
