##################################################################
# FACILITY:
10
##################################################################
#
cannotOpenDocument          Cannot open document '%0' : %1
cannotCreateDocument        Cannot create document: %0
cannotPrintDocument         Cannot print document: %0
initializationError         Initialization error: %0
representationError         Representation error: %0
editingError                Editing error: %0
cantLoadSchema              Can't load schema by URI: %0
undeclaredEntity            Reference to undeclared entity '%0': empty immutable entity reference created
installationProblem         An installation problem detected. Please reinstall Serna.
xincludeError               XInclude fallback or resource error, href='%0'
xincludeError2              XInclude fallback or resource error, href='%0', xpointer='%1'
# TOC handling errors
tocStylesheetNotFound       TOC stylesheet '%0': doesn't exist
tocStylesheetEmptyResult    TOC stylesheet '%0': produces empty output
tocStylesheetXsltError      TOC stylesheet '%0': an error occurred when doing XSLT
tocUnknownError             Unknown error '%0', TOC stylesheet: '%1'
# License check messages
licenseWillExpire           License will expire in %0 day(s).
licenseCopyFail             Error copying license file from "%0" to "%1"
licenseExpired              License has expired. Visit http://www.syntext.com/products/serna for details.
licenseWrongPlatform        The license in file '%0' is not for this platform/operating system.
licenseNotFound             No valid license supplied. Serna cannot continue.
licenseIncompatibleVer      The current version of Serna is not compatible with this license.
licenseFileError            Error reading license file: '%0'
licenseIsInvalid            The license is not valid.
licenseIsObsolete           The license in file '%0' is obsolete for the current version. Use this license for earlier versions or buy a new license.
# Speller message
spellCheckerError           Spell checker error: '%0'
spellCheckerCannotInit      Spell checker cannot be initialized, possible installation or misconfiguration problem.
spellCheckerOk              Spell check completed.
spellCheckerEncodingError   Can't determine local encoding for dictionary '%0', possible installation or misconfiguration problem.
spellCheckerNoDictionaries  There are no dictionaries installed, possible installation or misconfiguration problem.
spellCheckerInvalidDict     There is no such dictionary: '%0'
spellCheckerUnknownXmlLang  Spell checker: '%0' while trying to check with language '%1' specified in 'xml:lang' attribute.
# fileutils messages
unableToRead                Cannot read from '%0'
unableToWrite               Cannot write to '%0'
cannotCopyFile              Cannot copy file from '%0' to '%1'
cannotUpdateTemplate        Cannot update configuration template '%1' from '%0'
# plugin message
pluginMessage               %0: %1
# misc
eulaReject                  Thank you for interesting in Serna!
