#
# Grove messages
#
1
##################################################################
ParserMessage       %0: %1
xiUrlExprEmpty      XInclude: both 'href' and 'xpointer' attributes are empty
xiCannotOpen        XInclude: cannot open URL '%0' for reading (%1)
xiUnresolvedExpr    XInclude: cannot resolve xpointer '%0'
xiRecursiveInclusion XInclude: attempt of recursive inclusion
xiNoDocElement      XInclude: '%0' does not contain document element
cantSaveDoc       Cannot save document: %0 (%1)
cantSaveEntity    Cannot save external entity: %0 (%1)
cantSaveSubdoc    Cannot save sub-document: %0 (%1)
